config/routes.rb
Rails.application.routes.draw do
  resources :termsofservices
  resources :notices
  resources :frequent_questions
  resources :business_questions
  get 'home/index'
  devise_for :users
  resources :private_questions
  
  post 'frequent_questions/:id/toggle' => 'frequent_questions#toggle'
  post 'notices/:id/toggle' => 'notices#toggle'
  post 'termsofservices/:id/toggle' => 'termsofservices#toggle'

  root 'business_questions#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/notice.rb
class Notice < ApplicationRecord
    def self.search(search, date_from, date_to)
        dateFiltered = self.all
        if !date_from.blank? && !date_to.blank?
            #convert mm/dd/yyyy string to yyyy-mm-dd format
            start_date = Date.strptime(date_from, '%m/%d/%Y').strftime('%Y-%m-%d')
            end_date = Date.strptime(date_to, '%m/%d/%Y').next_day(1).strftime('%Y-%m-%d')
            dateFiltered = self.where(created_at: start_date..end_date )
        end
        
        if !search.blank?
            @searched_notices = dateFiltered.where('title LIKE ? OR body LIKE ?', "%#{search}%","%#{search}%").order(created_at: :desc)
        else
            @searched_notices = dateFiltered.order(created_at: :desc)
        end
    end
end

app/controllers/notices_controller.rb
class NoticesController < ApplicationController
  before_action :set_notice, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, only: [:new, :create, :edit, :update, :destroy]

  def toggle
    @notice = Notice.find(params[:id])

    if @notice != nil? 
      @notice.update_attributes(:isshown => params[:isshown])
    else
      set_flash "Error, please try again."
    end
  end
  # GET /notices
  # GET /notices.json
  def index
    @searched_notices = Notice.search(params[:search], params[:date_from], params[:date_to])
    @pagy, @notices = pagy(@searched_notices, items:10) 
  end

  # GET /notices/1
  # GET /notices/1.json
  def show
  end

  # GET /notices/new
  def new
    @notice = Notice.new
  end

  # GET /notices/1/edit
  def edit
  end

  # POST /notices
  # POST /notices.json
  def create
    @notice = Notice.new(notice_params)

    respond_to do |format|
      if @notice.save
        format.html { redirect_to @notice, notice: 'Notice was successfully created.' }
        format.json { render :show, status: :created, location: @notice }
      else
        format.html { render :new }
        format.json { render json: @notice.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /notices/1
  # PATCH/PUT /notices/1.json
  def update
    respond_to do |format|
      if @notice.update(notice_params)
        format.html { redirect_to @notice, notice: 'Notice was successfully updated.' }
        format.json { render :show, status: :ok, location: @notice }
      else
        format.html { render :edit }
        format.json { render json: @notice.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /notices/1
  # DELETE /notices/1.json
  def destroy
    @notice.destroy
    respond_to do |format|
      format.html { redirect_to notices_url, notice: 'Notice was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_notice
      @notice = Notice.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def notice_params
      params.require(:notice).permit(:title, :body, :isshown, 
      :search, :date_from, :date_to)
    end
end

app/helpers/notices_helper.rb
module NoticesHelper
end

app/views/notices/_form.html.erb
<%= form_with(model: notice, local: true) do |form| %>
  <% if notice.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(notice.errors.count, "error") %> prohibited this notice from being saved:</h2>

      <ul>
      <% notice.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <table class="table table-bordered">
    <tbody>
      <tr>
        <th scope="row">전시여부</th>
        <td>
          <%= form.check_box :isshown %> 전시
        </td>
      </tr>
      <tr>
        <th scope="row">등록 날짜</th>
        <td><%= notice.created_at %></td>
      </tr>
      <tr>
        <th scope="row">제목</th>
        <td><%= form.text_field :title, class: "form-control" %></td>
      </tr>
      <tr>
        <th scope="row">내용</th>
        <td>
          <%= tinymce :language => "en" %>
          <%= form.text_area :body, id: :post_content, class: "form-control tinymce", rows: "15" %>
        </td>
      </tr>
    </tbody>
  </table>
  
  <div class="actions">
    <%= form.submit "제출하기", class: "btn btn-primary pull-right" %>
  </div>
  
<% end %>

app/views/notices/edit.html.erb
<h1>Editing Notice</h1>

<%= render 'form', notice: @notice %>

<%= link_to '보기', @notice, class: "btn btn-success" %> |
<%= link_to '목록', notices_path, class: "btn btn-info" %>

app/views/notices/index.html.erb
<p id="notice"><%= notice %></p>

<div class="row">
  <div class="col-sm-3">
    <div class="panel panel-default">
        <div class="panel-heading">
        게시판 관리
        </div>
        <div class="panel-body">
          <div class="list_group">
            <a href="<%= business_questions_path %>" class="list-group-item">Business 게시판</a>
            <a href="<%= private_questions_path %>" class="list-group-item">1:1 문의 게시판</a>
            <a href="<%= frequent_questions_path %>" class="list-group-item">FAQ 게시판</a>
            <a href="<%= notices_path %>" class="list-group-item">공지사항</a>
            <a href="<%= termsofservices_path %>" class="list-group-item">약관</a>
          </div>
        </div>
      </div>
  </div>
  
  <div class="col-sm-9">
    <%= form_tag notices_path, :method => "get" do %>
      <div class="input-group">
        <%= text_field_tag :search, params[:search], placeholder: "제목/내용 검색", class: "form-control" %>
        <div class="input-group-btn">
          <%= submit_tag "검색", :class => 'btn btn-default' %>
        </div>
      </div>
      <br>
      <div class="input-group date form-inline">
        <div class="input-group-addon">
          <span class="glyphicon glyphicon-th"></span>
        </div>
        <%= text_field_tag :date_from, params[:date_from], placeholder: "시작 날짜", size: 9, data: {provide: 'datepicker'}, class: 'form-control' %>
      
        <div class="input-group-addon">
            <span class="glyphicon glyphicon-th"></span>
        </div>
        <%= text_field_tag :date_to, params[:date_to], placeholder: "끝 날짜", size: 9, data: {provide: 'datepicker'}, class: 'form-control' %>
      </div>
    <% end %>
  </div>
</div>

<table class="table table-bordered table-hover">
  <thead>
    <tr>
      <th>제목</th>
      <th>전시여부</th>
      <th>등록일시</th>
      <th colspan="2">관리</th>
    </tr>
  </thead>

  <tbody>
    <% @notices.each do |notice| %>
      <tr>
        <td><%= link_to "#{notice.title}", notice %></td>
        <td>
          <%= check_box_tag 'isshown', notice.id, notice.isshown,
              data: {
                remote: true,
                url: url_for(action: :toggle, id: notice.id),
                method: "POST"
              } %>
        </td>
        <td><%= notice.created_at.strftime('%Y-%m-%d %H:%M') %></td>
        <td><%= link_to '수정', edit_notice_path(notice) %></td>
        <td><%= link_to '삭제', notice, method: :delete, data: { confirm: '정말로 삭제하시겠습니까?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>
<!--Pagination Number At here-->
<nav class="text-center">
  <%== pagy_bootstrap_nav_js(@pagy) %>
  <script> Pagy.init() </script>
</nav>
<br>

<%= link_to '공지사항 작성하기', new_notice_path, class: "btn btn-default pull-right" %>

app/views/notices/new.html.erb
<h1>공지사항 올리기</h1>

<%= render 'form', notice: @notice %>

<%= link_to '목록', notices_path, class: "btn btn-info" %>
<br><br>

app/views/notices/show.html.erb
<table class="table table-bordered">
  <tbody>
    <tr>
      <th scope="row">전시 여부</th>
      <td>
        <%= check_box "notice", "isshown", {:checked => @notice.isshown, :disabled => true} %>
      </td>
    </tr>
    <tr>
      <th scope="row">등록날짜</th>
      <td><%= @notice.created_at.strftime('%Y-%m-%d %H:%M') %></td>
    </tr>
    <tr>
      <th scope="row">제목</th>
      <td><%= @notice.title %></td>
    </tr>
    <tr>
      <th scope="row">내용</th>
      <td><%= @notice.body.html_safe %></td>
    </tr>
  </tbody>
</table>

<%= link_to '수정', edit_notice_path(@notice), class: "btn btn-success" %> |
<%= link_to '목록', notices_path, class: "btn btn-info" %>