config/routes.rb
Rails.application.routes.draw do
  resources :termsofservices
  resources :notices
  resources :frequent_questions
  resources :business_questions
  get 'home/index'
  devise_for :users
  resources :private_questions
  
  post 'frequent_questions/:id/toggle' => 'frequent_questions#toggle'
  post 'notices/:id/toggle' => 'notices#toggle'
  post 'termsofservices/:id/toggle' => 'termsofservices#toggle'

  root 'business_questions#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/termsofservice.rb
class Termsofservice < ApplicationRecord
    enum category: [:terms_use, :privacy_policy, :personal_info]
    def self.search(search, date_from, date_to)
        dateFiltered = self.all
        if !date_from.blank? && !date_to.blank?
            #convert mm/dd/yyyy string to yyyy-mm-dd format
            start_date = Date.strptime(date_from, '%m/%d/%Y').strftime('%Y-%m-%d')
            end_date = Date.strptime(date_to, '%m/%d/%Y').next_day(1).strftime('%Y-%m-%d')
            dateFiltered = self.where(created_at: start_date..end_date )
        end
        
        if !search.blank?
            @searched_termsofservices = dateFiltered.where('title LIKE ? OR body LIKE ?', "%#{search}%","%#{search}%").order(created_at: :desc)
        else
            @searched_termsofservices = dateFiltered.order(created_at: :desc)
        end
    end
end

app/controllers/termsofservices_controller.rb
class TermsofservicesController < ApplicationController
  before_action :set_termsofservice, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, only: [:new, :create, :edit, :update, :destroy]


  def toggle
    @termsofservice = Termsofservice.find(params[:id])

    if @termsofservice != nil? 
      @termsofservice.update_attributes(:isshown => params[:isshown])
    else
      set_flash "Error, please try again."
    end
  end
  # GET /termsofservices
  # GET /termsofservices.json
  def index
    @searched_termsofservices = Termsofservice.search(params[:search], params[:date_from], params[:date_to])
    @pagy, @termsofservices = pagy(@searched_termsofservices, items:10)
  end

  # GET /termsofservices/1
  # GET /termsofservices/1.json
  def show
  end

  # GET /termsofservices/new
  def new
    @termsofservice = Termsofservice.new
  end

  # GET /termsofservices/1/edit
  def edit
  end

  # POST /termsofservices
  # POST /termsofservices.json
  def create
    @termsofservice = Termsofservice.new(termsofservice_params)

    respond_to do |format|
      if @termsofservice.save
        format.html { redirect_to @termsofservice, notice: 'Termsofservice was successfully created.' }
        format.json { render :show, status: :created, location: @termsofservice }
      else
        format.html { render :new }
        format.json { render json: @termsofservice.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /termsofservices/1
  # PATCH/PUT /termsofservices/1.json
  def update
    respond_to do |format|
      if @termsofservice.update(termsofservice_params)
        format.html { redirect_to @termsofservice, notice: 'Termsofservice was successfully updated.' }
        format.json { render :show, status: :ok, location: @termsofservice }
      else
        format.html { render :edit }
        format.json { render json: @termsofservice.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /termsofservices/1
  # DELETE /termsofservices/1.json
  def destroy
    @termsofservice.destroy
    respond_to do |format|
      format.html { redirect_to termsofservices_url, notice: 'Termsofservice was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_termsofservice
      @termsofservice = Termsofservice.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def termsofservice_params
      params.require(:termsofservice).permit(:title, :body, :isshown, 
      :category,
      :search, :date_from, :date_to)
    end
end

app/helpers/termsofservices_helper.rb
module TermsofservicesHelper
end

app/views/termsofservices/_form.html.erb
<%= form_with(model: termsofservice, local: true) do |form| %>
  <% if termsofservice.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(termsofservice.errors.count, "error") %> prohibited this termsofservice from being saved:</h2>

      <ul>
      <% termsofservice.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>


  <table class="table table-bordered">
    <tbody>
      <tr>
        <th scope="row">전시여부</th>
        <td>
          <%= form.check_box :isshown %> 전시
        </td>
      </tr>
      <tr>
        <th scope="row">등록 날짜</th>
        <td><%= termsofservice.created_at %></td>
      </tr>
      <tr>
        <th scope="row">카테고리</th>
        <td>
          <%= form.select :category, Termsofservice.categories.keys, {}, { class: 'form-control' } %>
        </td>
      </tr>
      <tr>
        <th scope="row">제목</th>
        <td><%= form.text_field :title, class: "form-control" %></td>
      </tr>
      <tr>
        <th scope="row">내용</th>
        <td>
          <%= tinymce :language => "en" %>
          <%= form.text_area :body, id: :post_content, class: "form-control tinymce", rows: "15" %>
        </td>
      </tr>
    </tbody>
  </table>

  <div class="actions">
    <%= form.submit "제출하기", class: "btn btn-primary pull-right" %>
  </div>
<% end %>

app/views/termsofservices/edit.html.erb
<h1>약관 수정하기</h1>

<%= render 'form', termsofservice: @termsofservice %>

<%= link_to '보기', @termsofservice, class: "btn btn-success" %> |
<%= link_to '목록', termsofservices_path, class: "btn btn-info" %>
<br><br>

app/views/termsofservices/index.html.erb
<p id="notice"><%= notice %></p>

<div class="row">
  <div class="col-sm-3">
    <div class="panel panel-default">
        <div class="panel-heading">
        게시판 관리
        </div>
        <div class="panel-body">
          <div class="list_group">
            <a href="<%= business_questions_path %>" class="list-group-item">Business 게시판</a>
            <a href="<%= private_questions_path %>" class="list-group-item">1:1 문의 게시판</a>
            <a href="<%= frequent_questions_path %>" class="list-group-item">FAQ 게시판</a>
            <a href="<%= notices_path %>" class="list-group-item">공지사항</a>
            <a href="<%= termsofservices_path %>" class="list-group-item">약관</a>
          </div>
        </div>
      </div>
  </div>
  
  <div class="col-sm-9">
    <%= form_tag termsofservices_path, :method => "get" do %>
      <div class="input-group">
        <%= text_field_tag :search, params[:search], placeholder: "제목/내용 검색", class: "form-control" %>
        <div class="input-group-btn">
          <%= submit_tag "검색", :class => 'btn btn-default' %>
        </div>
      </div>
      <br>
      <div class="input-group date form-inline">
        <div class="input-group-addon">
          <span class="glyphicon glyphicon-th"></span>
        </div>
        <%= text_field_tag :date_from, params[:date_from], placeholder: "시작 날짜", size: 9, data: {provide: 'datepicker'}, class: 'form-control' %>
      
        <div class="input-group-addon">
            <span class="glyphicon glyphicon-th"></span>
        </div>
        <%= text_field_tag :date_to, params[:date_to], placeholder: "끝 날짜", size: 9, data: {provide: 'datepicker'}, class: 'form-control' %>
      </div>
    <% end %>
  </div>
</div>

<table class="table table-bordered table-hover">
  <thead>
    <tr>
      <th>카테고리</th>
      <th>제목</th>
      <th>전시여부</th>
      <th>등록일시</th>
      <th colspan="2">관리</th>
    </tr>
  </thead>

  <tbody>
    <% @termsofservices.each do |termsofservice| %>
      <tr>
        <td>
          <%= Termsofservice.human_enum_name(:category, termsofservice.category) %>
        </td>
        <td>
          <%= link_to "#{termsofservice.title}", termsofservice %>
        </td>
        <td>
          <%= check_box_tag 'isshown', termsofservice.id, termsofservice.isshown,
              data: {
                remote: true,
                url: url_for(action: :toggle, id: termsofservice.id),
                method: "POST"
              } %>
        </td>
        <td><%= termsofservice.created_at.strftime('%Y-%m-%d %H:%M') %></td>
        <td><%= link_to '수정', edit_termsofservice_path(termsofservice) %></td>
        <td><%= link_to '삭제', termsofservice, method: :delete, data: { confirm: '정말로 삭제하시겠습니까?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>
<!--Pagination Number At here-->
<nav class="text-center">
  <%== pagy_bootstrap_nav_js(@pagy) %>
  <script> Pagy.init() </script>
</nav>
<br>

<%= link_to '약관 작성하기', new_termsofservice_path, class: "btn btn-default pull-right" %>

app/views/termsofservices/new.html.erb
<h1>약관 작성하기</h1>

<%= render 'form', termsofservice: @termsofservice %>

<%= link_to '목록', termsofservices_path, class: "btn btn-info" %>
<br><br>

app/views/termsofservices/show.html.erb
<table class="table table-bordered">
  <tbody>
    <tr>
      <th scope="row">전시 여부</th>
      <td>
        <%= check_box "termsofservice", "isshown", {:checked => @termsofservice.isshown, :disabled => true} %>
      </td>
    </tr>
    <tr>
      <th scope="row">등록날짜</th>
      <td><%= @termsofservice.created_at.strftime('%Y-%m-%d %H:%M') %></td>
    </tr>
    <tr>
      <th scope="row">카테고리</th>
      <td>
        <%= Termsofservice.human_enum_name(:category, @termsofservice.category) %>
      </td>
    </tr>
    <tr>
      <th scope="row">제목</th>
      <td><%= @termsofservice.title %></td>
    </tr>
    <tr>
      <th scope="row">내용</th>
      <td><%= @termsofservice.body.html_safe %></td>
    </tr>
  </tbody>
</table>

<%= link_to '수정', edit_termsofservice_path(@termsofservice), class: "btn btn-success" %> |
<%= link_to '목록', termsofservices_path, class: "btn btn-info" %>
<br><br>