config/routes.rb
Rails.application.routes.draw do
  resources :termsofservices
  resources :notices
  resources :frequent_questions
  resources :business_questions
  get 'home/index'
  devise_for :users
  resources :private_questions
  
  post 'frequent_questions/:id/toggle' => 'frequent_questions#toggle'
  post 'notices/:id/toggle' => 'notices#toggle'
  post 'termsofservices/:id/toggle' => 'termsofservices#toggle'

  root 'business_questions#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/frequent_question.rb
class FrequentQuestion < ApplicationRecord
    enum question_type: [:member, :pay_order, :shipping, :coupon_point, :cancel_return, :others]
    
    def self.search(search, date_from, date_to)
        dateFiltered = self.all
        if !date_from.blank? && !date_to.blank?
            #convert mm/dd/yyyy string to yyyy-mm-dd format
            start_date = Date.strptime(date_from, '%m/%d/%Y').strftime('%Y-%m-%d')
            end_date = Date.strptime(date_to, '%m/%d/%Y').next_day(1).strftime('%Y-%m-%d')
            dateFiltered = self.where(created_at: start_date..end_date )
        end
        
        if !search.blank?
            @searched_frequent_questions = dateFiltered.where('title LIKE ? OR body LIKE ?', "%#{search}%","%#{search}%").order(created_at: :desc)
        else
            @searched_frequent_questions = dateFiltered.order(created_at: :desc)
        end
    end
end

app/controllers/frequent_questions_controller.rb
class FrequentQuestionsController < ApplicationController
  before_action :set_frequent_question, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, only: [:new, :create, :edit, :update, :destroy]

  def toggle
    @frequent_question = FrequentQuestion.find(params[:id])

    if @frequent_question != nil? 
      @frequent_question.update_attributes(:isshown => params[:isshown])
    else
      set_flash "Error, please try again."
    end
  end

  # GET /frequent_questions
  # GET /frequent_questions.json
  def index
    @searched_frequent_questions = FrequentQuestion.search(params[:search], params[:date_from], params[:date_to])
    @pagy, @frequent_questions = pagy(@searched_frequent_questions, items:10) 
  end
  # GET /frequent_questions/1
  # GET /frequent_questions/1.json
  def show
  end

  # GET /frequent_questions/new
  def new
    @frequent_question = FrequentQuestion.new
  end

  # GET /frequent_questions/1/edit
  def edit
  end

  # POST /frequent_questions
  # POST /frequent_questions.json
  def create
    @frequent_question = FrequentQuestion.new(frequent_question_params)

    respond_to do |format|
      if @frequent_question.save
        format.html { redirect_to @frequent_question, notice: 'Frequent question was successfully created.' }
        format.json { render :show, status: :created, location: @frequent_question }
      else
        format.html { render :new }
        format.json { render json: @frequent_question.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /frequent_questions/1
  # PATCH/PUT /frequent_questions/1.json
  def update
    respond_to do |format|
      if @frequent_question.update(frequent_question_params)
        format.html { redirect_to @frequent_question, notice: 'Frequent question was successfully updated.' }
        format.json { render :show, status: :ok, location: @frequent_question }
      else
        format.html { render :edit }
        format.json { render json: @frequent_question.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /frequent_questions/1
  # DELETE /frequent_questions/1.json
  def destroy
    @frequent_question.destroy
    respond_to do |format|
      format.html { redirect_to frequent_questions_url, notice: 'Frequent question was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_frequent_question
      @frequent_question = FrequentQuestion.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def frequent_question_params
      params.require(:frequent_question).permit(:title, :body, :isshown, 
      :question_type, 
      :search, :date_from, :date_to)
    end
end

app/helpers/frequent_questions_helper.rb
module FrequentQuestionsHelper
end

app/views/frequent_questions/_form.html.erb
<%= form_with(model: frequent_question, local: true) do |form| %>
  <% if frequent_question.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(frequent_question.errors.count, "error") %> prohibited this frequent_question from being saved:</h2>

      <ul>
      <% frequent_question.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <table class="table table-bordered">
    <tbody>
      <tr>
        <th scope="row">카테고리</th>
        <td>
          <%= form.select :question_type, FrequentQuestion.question_types.keys, {}, { class: 'form-control' } %>
        </td>
      </tr>
      <tr>
        <th scope="row">전시여부</th>
        <td>
          <%= form.check_box :isshown %> 전시
        </td>
      </tr>
      <tr>
        <th scope="row">등록 날짜</th>
        <td><%= frequent_question.created_at %></td>
      </tr>
      <tr>
        <th scope="row">FAQ 질문</th>
        <td><%= form.text_field :title, class: "form-control" %></td>
      </tr>
      <tr>
        <th scope="row">FAQ 답변</th>
        <td>
          <%= tinymce :language => "en" %>
          <%= form.text_area :body, id: :post_content, class: "form-control tinymce", rows: "15" %>
        </td>
      </tr>
    </tbody>
  </table>

  <div class="actions">
    <%= form.submit "제출하기", class: "btn btn-primary pull-right" %>
  </div>
<% end %>

app/views/frequent_questions/edit.html.erb
<h1>FAQ - 자주 묻는 질문</h1>

<%= render 'form', frequent_question: @frequent_question %>

<%= link_to '보기', @frequent_question, class: "btn btn-success" %> |
<%= link_to '목록', frequent_questions_path, class: "btn btn-info" %>
<br><br>

app/views/frequent_questions/index.html.erb
<p id="notice"><%= notice %></p>

<div class="row">
  <div class="col-sm-3">
    <div class="panel panel-default">
        <div class="panel-heading">
        게시판 관리
        </div>
        <div class="panel-body">
          <div class="list_group">
            <a href="<%= business_questions_path %>" class="list-group-item">Business 게시판</a>
            <a href="<%= private_questions_path %>" class="list-group-item">1:1 문의 게시판</a>
            <a href="<%= frequent_questions_path %>" class="list-group-item">FAQ 게시판</a>
            <a href="<%= notices_path %>" class="list-group-item">공지사항</a>
            <a href="<%= termsofservices_path %>" class="list-group-item">약관</a>
          </div>
        </div>
      </div>
  </div>
  
  <div class="col-sm-9">
    <%= form_tag frequent_questions_path, :method => "get" do %>
      <div class="input-group">
        <%= text_field_tag :search, params[:search], placeholder: "제목/내용 검색", class: "form-control" %>
        <div class="input-group-btn">
          <%= submit_tag "검색", :class => 'btn btn-default' %>
        </div>
      </div>
      <br>
      <div class="input-group date form-inline">
        <div class="input-group-addon">
          <span class="glyphicon glyphicon-th"></span>
        </div>
        <%= text_field_tag :date_from, params[:date_from], placeholder: "시작 날짜", size: 9, data: {provide: 'datepicker'}, class: 'form-control' %>
      
        <div class="input-group-addon">
            <span class="glyphicon glyphicon-th"></span>
        </div>
        <%= text_field_tag :date_to, params[:date_to], placeholder: "끝 날짜", size: 9, data: {provide: 'datepicker'}, class: 'form-control' %>
      </div>
    <% end %>
  </div>
</div>

<table class="table table-bordered table-hover">
  <thead>
    <tr>
      <th>카테고리</th>
      <th>제목</th>
      <th>전시여부</th>
      <th>등록일시</th>
      <th colspan="2">관리</th>
    </tr>
  </thead>

  <tbody>
    <% @frequent_questions.each do |frequent_question| %>
      <tr>
        <td>
          <%= FrequentQuestion.human_enum_name(:question_type, frequent_question.question_type) %>
        </td>
        <td>
          <%= link_to "#{frequent_question.title}", frequent_question %>
        </td>
        <td>
          <%= check_box_tag 'isshown', frequent_question.id, frequent_question.isshown,
              data: {
                remote: true,
                url: url_for(action: :toggle, id: frequent_question.id),
                method: "POST"
              } %>
        </td>
        <td><%= frequent_question.created_at.strftime('%Y-%m-%d %H:%M') %></td>
        <td><%= link_to '수정', edit_frequent_question_path(frequent_question) %></td>
        <td><%= link_to '삭제', frequent_question, method: :delete, data: { confirm: '정말로 삭제하시겠습니까?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>
<!--Pagination Number At here-->
<nav class="text-center">
  <%== pagy_bootstrap_nav_js(@pagy) %>
  <script> Pagy.init() </script>
</nav>
<br>

<%= link_to 'FAQ 작성하기', new_frequent_question_path, class: "btn btn-default pull-right" %>

app/views/frequent_questions/new.html.erb
<h1>FAQ 작성하기</h1>

<%= render 'form', frequent_question: @frequent_question %>

<%= link_to '목록', frequent_questions_path, class: "btn btn-info" %>
<br><br>

app/views/frequent_questions/show.html.erb
<table class="table table-bordered">
  <tbody>
    <tr>
      <th scope="row">카테고리</th>
      <td>
        <%= FrequentQuestion.human_enum_name(:question_type, @frequent_question.question_type) %>
      </td>
    </tr>
    <tr>
      <th scope="row">전시 여부</th>
      <td>
        <%= check_box "frequent_question", "isshown", {:checked => @frequent_question.isshown, :disabled => true} %>
      </td>
    </tr>
    <tr>
      <th scope="row">등록날짜</th>
      <td><%= @frequent_question.created_at.strftime('%Y-%m-%d %H:%M') %></td>
    </tr>
    <tr>
      <th scope="row">FAQ 질문</th>
      <td><%= @frequent_question.title %></td>
    </tr>
    <tr>
      <th scope="row">FAQ 답변</th>
      <td><%= @frequent_question.body.html_safe %></td>
    </tr>
  </tbody>
</table>

<%= link_to '수정', edit_frequent_question_path(@frequent_question), class: "btn btn-success" %> |
<%= link_to '목록', frequent_questions_path, class: "btn btn-info" %>
<br><br>