config/routes.rb
Rails.application.routes.draw do
  resources :termsofservices
  resources :notices
  resources :frequent_questions
  resources :business_questions
  get 'home/index'
  devise_for :users
  resources :private_questions
  
  post 'frequent_questions/:id/toggle' => 'frequent_questions#toggle'
  post 'notices/:id/toggle' => 'notices#toggle'
  post 'termsofservices/:id/toggle' => 'termsofservices#toggle'

  root 'business_questions#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/private_question.rb
class PrivateQuestion < ApplicationRecord
    enum question_type: [:order_cancel, :order_pay, :product_info, :product_return, :others]
    enum reply_state: [:waiting, :fulfilled]
    belongs_to :user
    
    def self.search(search, date_from, date_to)
        dateFiltered = self.all
        if !date_from.blank? && !date_to.blank?
            #convert mm/dd/yyyy string to yyyy-mm-dd format
            start_date = Date.strptime(date_from, '%m/%d/%Y').strftime('%Y-%m-%d')
            end_date = Date.strptime(date_to, '%m/%d/%Y').next_day(1).strftime('%Y-%m-%d')
            dateFiltered = self.where(created_at: start_date..end_date )
        end
        
        if !search.blank?
            #search with user name first
            searched_user = User.where( 'name LIKE ?', "%#{search}%" )
            if !searched_user.empty?
                @searched_private_questions = dateFiltered.where(user: searched_user).order(created_at: :desc)
            else
                #if search keyword is not username, search in title and body context
                @searched_private_questions = dateFiltered.where('title LIKE ? OR body LIKE ?', "%#{search}%","%#{search}%").order(created_at: :desc)
            end
        else
            @searched_private_questions = dateFiltered.order(created_at: :desc)
        end
    end
    
end

app/controllers/private_questions_controller.rb
class PrivateQuestionsController < ApplicationController
  before_action :set_private_question, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!

  # GET /private_questions
  # GET /private_questions.json
  def index
    @searched_private_questions = PrivateQuestion.search(params[:search], params[:date_from], params[:date_to])
    @pagy, @private_questions = pagy(@searched_private_questions, items:10) 
  end

  # GET /private_questions/1
  # GET /private_questions/1.json
  def show
  end

  # GET /private_questions/new
  def new
    @private_question = PrivateQuestion.new
  end

  # GET /private_questions/1/edit
  def edit
  end

  # POST /private_questions
  # POST /private_questions.json
  def create
    @private_question = PrivateQuestion.new(private_question_params)
    @private_question.user_id = current_user.id

    respond_to do |format|
      if @private_question.save
        format.html { redirect_to @private_question, notice: 'Private question was successfully created.' }
        format.json { render :show, status: :created, location: @private_question }
      else
        format.html { render :new }
        format.json { render json: @private_question.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /private_questions/1
  # PATCH/PUT /private_questions/1.json
  def update
    respond_to do |format|
      if @private_question.update(private_question_params)
        format.html { redirect_to @private_question, notice: 'Private question was successfully updated.' }
        format.json { render :show, status: :ok, location: @private_question }
      else
        format.html { render :edit }
        format.json { render json: @private_question.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /private_questions/1
  # DELETE /private_questions/1.json
  def destroy
    @private_question.destroy
    respond_to do |format|
      format.html { redirect_to private_questions_url, notice: 'Private question was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_private_question
      @private_question = PrivateQuestion.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def private_question_params
      params.require(:private_question).permit(:title, :body, 
      :question_type, :reply_state, :reply_time, :reply_title, :reply_body, :reply_sms, :reply_email, 
      :search, :date_from, :date_to)
    end
end

app/helpers/private_questions_helper.rb
module PrivateQuestionsHelper
end

app/views/private_questions/_form.html.erb
<%= form_with(model: private_question, local: true) do |form| %>
  <% if private_question.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(private_question.errors.count, "error") %> prohibited this private_question from being saved:</h2>

      <ul>
      <% private_question.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <table class="table table-bordered">
    <tbody>
      <% if private_question.user != nil %>
      <tr>
        <th scope="row">작성자</th>
        <td><%= private_question.user.name %></td>
      </tr>
      <tr>
        <th scope="row">작성 날짜</th>
        <td><%= private_question.created_at %></td>
      </tr>
      <% end %>
      <tr>
        <th scope="row">질문 유형</th>
        <td><%= form.select :question_type, PrivateQuestion.question_types.keys, {}, { class: 'form-control' } %></td>
      </tr>
      <tr>
        <th scope="row">질문 제목</th>
        <td><%= form.text_field :title, class: "form-control" %></td>
      </tr>
      <tr>
        <th scope="row">질문 내용</th>
        <td><%= form.text_area :body, class: "form-control", rows: "10" %></td>
      </tr>
      <tr>
        <th scope="row">답변 날짜</th>
        <td>
          <div class="form-inline">
            <%= form.datetime_select :reply_time,  { ampm: true, order: [:year, :month, :day] }, { class: "form-control" } %>  
          </div>
        </td>
      </tr>
      <tr>
        <th scope="row">답변 제목</th>
        <td><%= form.text_field :reply_title, class: "form-control" %></td>
      </tr>
      <tr>
        <th scope="row">답변 내용</th>
        <td>
          <%= tinymce :language => "en" %>
          <%= form.text_area :reply_body, id: :post_content, class: "form-control tinymce", rows: "15" %>
        </td>
      </tr>
      <tr>
        <th scope="row">문자 전송</th>
        <td><%= form.text_field :reply_sms, class: "form-control" %></td>
      </tr>
      <tr>
        <th scope="row">이메일 전송</th>
        <td><%= form.text_field :reply_email, class: "form-control" %></td>
      </tr>
    </tbody>
  </table>
  
  <div class="actions">
    <%= form.submit "제출하기", class: "btn btn-primary pull-right" %>
  </div>
<% end %>

app/views/private_questions/edit.html.erb
<h1>1:1 문의</h1>

<%= render 'form', private_question: @private_question %>

<%= link_to '보기', @private_question, class: "btn btn-success" %> |
<%= link_to '목록', private_questions_path, class: "btn btn-info" %>
<br><br>

app/views/private_questions/index.html.erb
<p id="notice"><%= notice %></p>

<div class="row">
  <div class="col-sm-3">
    <div class="panel panel-default">
        <div class="panel-heading">
        게시판 관리
        </div>
        <div class="panel-body">
          <div class="list_group">
            <a href="<%= business_questions_path %>" class="list-group-item">Business 게시판</a>
            <a href="<%= private_questions_path %>" class="list-group-item">1:1 문의 게시판</a>
            <a href="<%= frequent_questions_path %>" class="list-group-item">FAQ 게시판</a>
            <a href="<%= notices_path %>" class="list-group-item">공지사항</a>
            <a href="<%= termsofservices_path %>" class="list-group-item">약관</a>
          </div>
        </div>
      </div>
  </div>
  
  <div class="col-sm-9">
    <%= form_tag private_questions_path, :method => "get" do %>
      <div class="input-group">
        <%= text_field_tag :search, params[:search], placeholder: "작성자/제목/내용 검색", class: "form-control" %>
        <div class="input-group-btn">
          <%= submit_tag "검색", :class => 'btn btn-default' %>
        </div>
      </div>
      <br>
      <div class="input-group date form-inline">
        <div class="input-group-addon">
          <span class="glyphicon glyphicon-th"></span>
        </div>
        <%= text_field_tag :date_from, params[:date_from], placeholder: "시작 날짜", size: 9, data: {provide: 'datepicker'}, class: 'form-control' %>
      
        <div class="input-group-addon">
            <span class="glyphicon glyphicon-th"></span>
        </div>
        <%= text_field_tag :date_to, params[:date_to], placeholder: "끝 날짜", size: 9, data: {provide: 'datepicker'}, class: 'form-control' %>
      </div>
    <% end %>
  </div>

</div>
  
<table class="table table-bordered table-hover">
  <thead>
    <tr>
      <th>작성자</th>
      <th>질문 유형</th>
      <th>제목</th>
      <th>문의 날짜</th>
      <th>답변 상태</th>
      <th colspan="2">관리</th>
    </tr>
  </thead>

  <tbody>
    <% @private_questions.each do |private_question| %>
      <tr>
        <td><%= private_question.user.name %></td>
        <td>
          <%= PrivateQuestion.human_enum_name(:question_type, private_question.question_type) %>
        </td>
        <td>
          <%= link_to "#{private_question.title}", private_question %>
        </td>
        <td><%= private_question.created_at.strftime('%Y-%m-%d %H:%M') %></td>
        <td>
          <% if private_question.reply_body.empty? %>
            <span>답변대기</span>
            <%= link_to '답변등록', edit_private_question_path(private_question), :class => "btn btn-success pull-right" %>
          <% else %>
            <span>답변완료</span>
            <%= link_to '답변수정', edit_private_question_path(private_question), :class => "btn btn-info pull-right" %>
          <% end %>
        </td>
        <td><%= link_to '수정', edit_private_question_path(private_question) %></td>
        <td><%= link_to '삭제', private_question, method: :delete, data: { confirm: '정말로 삭제하시겠습니까?' } %></td>
      </tr>
    <% end %>
  </tbody>
  
</table>

<!--Pagination Number At here-->
<nav class="text-center">
  <%== pagy_bootstrap_nav_js(@pagy) %>
  <script> Pagy.init() </script>
</nav>

<%= link_to '1:1 문의하기', new_private_question_path, class: "btn btn-default pull-right" %>

app/views/private_questions/new.html.erb
<h1>1:1 문의 작성하기</h1>

<%= render 'form', private_question: @private_question %>

<%= link_to '목록', private_questions_path, class: "btn btn-info" %>
<br><br>

app/views/private_questions/show.html.erb
<table class="table table-bordered">
  <tbody>
    <tr>
      <th scope="row">작성자</th>
      <td><%= @private_question.user.name %></td>
    </tr>
    <tr>
      <th scope="row">작성 날짜</th>
      <td><%= @private_question.created_at.strftime('%Y-%m-%d %H:%M') %></td>
    </tr>
    <tr>
      <th scope="row">질문 유형</th>
      <td>
        <%= PrivateQuestion.human_enum_name(:question_type, @private_question.question_type) %>
      </td>
    </tr>
    <tr>
      <th scope="row">질문 제목</th>
      <td><%= @private_question.title %></td>
    </tr>
    <tr>
      <th scope="row">질문 내용</th>
      <td><%= @private_question.body %></td>
    </tr>
    <tr>
      <th scope="row">답변 날짜</th>
      <td><%= @private_question.reply_time %></td>
    </tr>
    <tr>
      <th scope="row">답변 제목</th>
      <td><%= @private_question.reply_title %></td>
    </tr> 
    <tr>
      <th scope="row">답변 내용</th>
      <td><%= @private_question.reply_body.html_safe %></td>
    </tr>
    <tr>
      <th scope="row">연락처</th>
      <td><%= @private_question.reply_sms %></td>
    </tr>
    <tr>
      <th scope="row">이메일</th>
      <td><%= @private_question.reply_email %></td>
    </tr>
  </tbody>
</table>

<%= link_to '수정', edit_private_question_path(@private_question), class: "btn btn-success" %> |
<%= link_to '목록', private_questions_path, class: "btn btn-info" %>
<br><br>